### ISSUE TITLE
Webpack development reloading error

### ISSUE THREAD

**Issue by Rowno** [sveltejs/sapper-template#153] opened 2019-06-11 06:33 UTC
Running the Webpack example with zero changes and then editing `src/routes/index.svelte` results in the following error in the browser (and the page doesn't reload):
```
Uncaught TypeError: Cannot read property 'status' of undefined
  at check (sapper-dev-client.js:6)
  at EventSource.source.onmessage (sapper-dev-client.js:37)
```

Which is this code:

![image](https://user-images.githubusercontent.com/605501/59248717-113e4080-8bd8-11e9-9ab0-5e89129043d7.png)

**Comment by Rowno** [comment] 2019-06-11 06:37
Found a workaround, changing the [`dev` script](https://github.com/sveltejs/sapper-template/blob/a1b567dc08caa73ff7d3e05653c3ffe339c202ec/package_template.json#L6) to this fixes the issue:
```
sapper dev --hot=false
```

**Comment by samosaara** [comment] 2019-09-03 12:54
Well I'm sorry but that doesn't fix the problem just avoids it... But is this issue even related to this repo? It appears the issue is in sapper internal scripts themselves rather than this template...

**Comment by antony** [comment] 2020-02-15 11:19
Closing in favour of the linked issue in Sapper.

**Closed by antony** 2020-02-15 11:19 UTC
